### ISSUE TITLE
Maven Central updates

### ISSUE THREAD

**Issue by jodastephen** [cbeust/jcommander#444] opened 2018-05-04 15:22 UTC
It seems that v1.73 and v1.74 never made it to [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.beust%22%20AND%20a%3A%22jcommander%22). This is awkward as I'd like to use the `Automatic-Module-Name` so I can move to Java 9 and beyond.

Would appreciate if v1.74 could be pushed. Thanks.

**Comment by juherr** [comment] 2018-06-24 19:22
Duplicate of https://github.com/cbeust/jcommander/issues/441

**Comment by cbeust** [comment] 2019-08-14 04:19
Fixed, 1.75 now available on Maven Central:  https://search.maven.org/artifact/com.beust/jcommander/1.75/jar

**Closed by cbeust** 2019-08-14 04:19 UTC
